
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-03T17:25:39-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "03a7138ad47761c9a9f83c614644d08aa614ac4e",
 "version": "0+untagged.191.g03a7138.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
